### ISSUE TITLE
Update readme of demo project

### ISSUE THREAD

**Issue by deepakkumarrai** [rtkhanas/icloud-session#3]
Hi @rtkhanas, 

How can I run this demo? please elaborate it. I did not get it "**The demo is not possible, because of cors. But it works on a server.**". please help me out.

**Comment by rosskhanas** [comment]
Hi @deepakkumarrai ,

Set your login and password here: https://github.com/rtkhanas/icloud-session/blob/master/demo-nodejs/login.js and run this file `node login.js`. You will authorize and also session file will be created. Then you can do `node load .js` and you will get list of contacts.

Hope it helps.

**Comment by deepakkumarrai** [comment]
@rtkhanas 
Thanks it is very helpful for me

**Comment by deepakkumarrai** [comment]
@rtkhanas ,

Hey man, can I create new contacts or contact groups back to my Icloud account?

**Comment by rosskhanas** [comment]
@deepakkumarrai I guess yes, it is more about iCloud API. This lob is just an auth library so you can build spmething on top of it as I did with https://github.com/rtkhanas/icloud-contacts for getting a list of contacts.
